version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: coffee-db-mysql
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: coffee_shop_db
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    container_name: coffee-backend
    build: .
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coffee_shop_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
